# .github/workflows/workflow.yml
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: sumiranagg/hello-action-ks@master
      with:
        who-to-greet: 'Sumiran'
      id: hello
    - run: echo "The time was ${{ steps.hello.outputs.time }}"
