# .github/workflows/workflow.yml
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ./hello-action
      with:
        who-to-greet: 'Mundo'
      id: hello
    - run: echo "The time was ${{ steps.hello.outputs.time }}"
